### ISSUE TITLE
Pico W not runing firmware after custom compilation

### ISSUE THREAD

**Issue by gco33** [astlouys/Pico-Green-Clock#22]
Hello,

I have followed the guide to recompile firmware for a Pico W (copy Pico W CMakefile and remove comment before #define PICO_W, put my ssid and password for my WiFi network)

I was able to recompile without any error and was able to flash to the mcu but nothing append after restart mcu (no flash led, no display, no sound).

I also have remarked that, firmware file size is bigger than precompiled one.

Thanks a lot for any help or tips.

**Comment by astlouys** [comment]
Hi GCO33,

Yeah, this problem was previously reported to me and even if I didn't investigate, I think it is related to the SDK update of last February...

You may want to read the discussion thread whose title is "Project builds ok but doesn't run on a Pico W". It is a good idea to read it all, but the answer to your problem is probably related to the "cyw43_arch_wifi_connect_blocking(...)" call. You may have to "unroll" the discussion thread to make sure you have access to all answers toward the end of the thread.

Let me know if you find a solution to your problem. 

As for the the size difference, it is probably related to options that are set differently (debug, optimizations, or the like)... I wouldn't care too much at this point.

May I ask you in which country you are ?

André

**Comment by gco33** [comment]
Hello André,

First of all, thanks a lot for fast answer.

I have tried to find thread with title you mentioned, but not yet found., I will continue my research ...

And for your question, I leave in south west of France, near Bordeaux.

Gilles

**Comment by astlouys** [comment]
Bonjour Gilles,

Je suis heureux de constater que la traduction française de plusieurs textes de l'horloge pourront aussi être utiles à d'autres que moi... (sourire)

Here is a "copy-paste" that I posted on another thread. I am confident that it will solve your problem. Let me know.

Beginning of extract:
=============
As you know, I crashed my development system in the last days and I had to rebuild it from scratch (although I had the source code Version 9.00 for the Pico-Green-Clock).

I rebuilt the Firmware Version 9.00 and I was surprised to realize that I got the same problem that you have. After investigating, I believe I found the problem. In the file "picow_ntp_client.c", around line 472 (I may have added or removed a few lines above...) the line that begins with "ReturnCode = cyw43_arch_wifi_connect_blocking(...)"

Replace the "blocking" by "timeout_ms" and add ",1000" as the last parameter at the end of the parenthesis. Please note that I'm providing this answer soon so that you can get out of your problem, and I haven't taken the time to analyze and test this "1000 milliseconds timeout". I think it should be OK, but experience may show that it may be decreased or it should be increased.

According to what I've read on the Net, the Pico W SDK libraries have been updated in February (it seems that with the new libraries, the Pico W now supports bluetooth !) and some change in the behaviour may explain the problems that you had.

End of extract:
=========

**Comment by gco33** [comment]
Bonjour André,

Effectivement, cela fonctionne maintenant. Merci pour indication.

Et bravo pour ce dévelopement au top.

I continue in english of reference of solution :
The fix mentioned in your extract has solve the problem (and value for timeout seem to be ok for my wifi network)

Bellow is the modification i made in **picow_ntp_client.c**
    ```
// 2023-04-21 : workaround to solve problem with latest version of pico-sdk
    // ReturnCode = cyw43_arch_wifi_connect_blocking(&FlashConfig.SSID[4], &FlashConfig.Password[4], CYW43_AUTH_WPA2_AES_PSK);
    ReturnCode = cyw43_arch_wifi_connect_timeout_ms(&FlashConfig.SSID[4], &FlashConfig.Password[4], CYW43_AUTH_WPA2_AES_PSK, 1000);
```

**Comment by astlouys** [comment]
Great Gilles !

I'm happy to realize that it also worked for you. Let me know if ever you add new functions and / or make some modifications to the Green Clock. I'm always curious to hear about experiences from other users.

Cheers.

André
