### ISSUE TITLE
Time synchronization via NTP with PicoW

### ISSUE THREAD

**Issue by FFF27** [astlouys/Pico-Green-Clock#9]
Seems like a good idea.

### Discussed in https://github.com/astlouys/Pico-Green-Clock/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **Spart-aaa** November 14, 2022</sup>
Hello Andre, 
first and foremost a big thank you for the incredible amount of effort you are putting into this project and the meticulous documentation. I am a big fan of all of the useful and well thought out features you came up with and your project has a prominent spot right at my desk every day.

I am opening this thread because I wanted to ask if it would be possible for you to implement an NTP based time-sync of the RTC at some point in the future.

I bought the Pico-Green-Clock a few months ago thinking it would be an easy task to run it based on a PicoW instead of the regular Pico and have the PicoW connect to a WiFi once per hour or so to pull in an always accurate time via NTP. However due to the fact that I have no experience at all with programming microcontrollers or C I have been failing at achieving this despite the fact that the pico-examples include an NTP client but I have no idea how to get the RTC of the clock to sync with the ntp data.

Another idea based on this would be to have an additional tiny webserver running to make the clock configurable via website directly, but that would be a whole new topic on itself.

Thank you very much for any help you can provide and best regards :)</div>

**Comment by astlouys** [comment]
I believe this is a good idea, even if the DS3231 real-time clock seems to do great job in keeping the time right over long period of time (this will give us more time to implement NTP :-)  ).

I'm currently investigating supporting clock display brightness by using PWM. If someone is volunteer to work on NTP, let us know. Otherwise, I could take a look at it after this PWM stuff...

**Comment by astlouys** [comment]
Hi Frank,

Your dream came true !

I just released Version 9.00 of the Firmware which adds support for NTP. I hope you will enjoy it !

Obviously, it does not re-sync the clock every hour, but frequently enough that you shouldn't have delay problems. If you require sub-second precision, the Green Clock is definitely the wrong tool for you ! (smile) More seriously, there are some "ethical rules" to follow when requesting NTP and one of them is about the access frequency. I wanted to make sure that users won't be blamed for DoS (Denial of Service) attack ! (So, I won't help users changing this frequency).

As for the Web server to make the configuration, I have no plan to work on this, to be honest. Since that now, the configuration is saved in Pico's flash, clock configuration is usually a one-time task (except if you use clock alarms and if you require changing them regularly). It could be an interesting small project for someone else, now that the Wi-Fi connection is already implemented.

I hope you'll enjoy, Frank !

André
